POST http://localhost:8080/servers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJZOEFPdUVGVmZxeXdvanBET0RtYjZsTUpWeVhMNkhsUSIsImV4cCI6MTczMzQyNzM3NCwiaWF0IjoxNzMzNDI2NDc0LCJuYmYiOjE3MzM0MjYxNzQsInJvbGVzIjpudWxsLCJzdWIiOiJDaXNwYToxMTM2In0.IDiLCkCYMzr6xIsfFHk2AHUO6vrT5gMn5-WZSuEuR7c

{
  "name": "GWP",
  "image": "image.png"
}
