POST http://localhost:8080/servers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJZOEFPdUVGVmZxeXdvanBET0RtYjZsTUpWeVhMNkhsUSIsImV4cCI6MTczMzI1MjMwNCwiaWF0IjoxNzMzMjUxNDA0LCJuYmYiOjE3MzMyNTExMDQsInN1YiI6IkNpc3BhOjE0MDkifQ.A--R6-pHGuXf7GpvYxvAI0CZbtPTdib3XGyrEB3niNE

{
  "name": "GWP",
  "image": "image.png",
  "owner_id": "Cispa:6802"
}
