GET http://localhost:8080/servers/6751f962d97d9c98be0cad26/invite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJZOEFPdUVGVmZxeXdvanBET0RtYjZsTUpWeVhMNkhsUSIsImV4cCI6MTczMzQyNjE2OCwiaWF0IjoxNzMzNDI1MjY4LCJuYmYiOjE3MzM0MjQ5NjgsInN1YiI6IkNpc3BhOjMzMjMifQ.TLdNdsLAf2uvBhAi5ELjQBrhJRPiF9UC5KsPHyTureo
